spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market_db
    username: market_user
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9031
  servlet:
    context-path: /foreigndebt-service
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic